# Examen Demo

In [8]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd

## 01
- Dado un diccionario con una lista de nombres de películas y el año concatenado, crear una función que devuelva un DataFrame con dos columnas:
  - Columna 1, el nombre de la película sin el año
  - Columna 2, el año de la película

In [4]:
movies = {'Name': ["Matrix - 1999", "Cadena Perpetua - 1994", "Parasitos - 2019", "Vengadores, Endgame - 2019", "Interstellar - 2014",
                   "Django Desencadenado - 2012", "El Padrino - 1972", "El Caballero Oscuro - 2008", "Erase Una Vez En America - 1984",
                   "El Senyor de los Anillos, La Comunidad del Anillo - 2001"]}
expected_output = pd.DataFrame({'Name':["Matrix", "Cadena Perpetua", "Parasitos", "Vengadores, Endgame", "Interstellar", "Django Desencadenado",
                                        "El Padrino", "El Caballero Oscuro", "Erase Una Vez En America", "El Senyor de los Anillos, La Comunidad del Anillo"],
                                'Year':["1999", "1994", "2019", "2019", "2014", "2012", "1972", "2008", "1984", "2001"]})
output = extract_year(movies)   # This will call your function extract_year
display(output)
assert(expected_output.equals(output))  # This will fail if the result is not as expected

                                                Name  Year
0                                             Matrix  1999
1                                    Cadena Perpetua  1994
2                                          Parasitos  2019
3                                Vengadores, Endgame  2019
4                                       Interstellar  2014
5                               Django Desencadenado  2012
6                                         El Padrino  1972
7                                El Caballero Oscuro  2008
8                           Erase Una Vez En America  1984
9  El Senyor de los Anillos, La Comunidad del Anillo  2001

In [1]:
# Your solution HERE !!!!
# Función que separa el nombre de la película y el año
def extract_year(movies):

    # Extrae únicamente el año del título
    def split_year(title):
        # Busca la posición del guion (-)
        index = title.index('-')
        # Devuelve el texto desde el guion hasta el final,
        # eliminando el guion y los espacios en blanco
        return title[index:].replace('-', '').strip()

    # Extrae únicamente el nombre de la película
    def remove_year(title):
        # Busca la posición del guion (-)
        index = title.index('-')
        # Devuelve el texto antes del guion
        return title[:index-1].strip()

    # Convierte el diccionario en un DataFrame
    df_movies = pd.DataFrame(movies)

    # Crea una nueva columna "Year" aplicando la función a cada título
    df_movies['Year'] = df_movies['Name'].apply(split_year)

    # Reemplaza la columna "Name" dejando solo el nombre de la película
    df_movies['Name'] = df_movies['Name'].apply(remove_year)

    # Devuelve el DataFrame con las columnas Name y Year separadas
    return df_movies

In [2]:
# Función que separa el nombre de la película y el año
def extract_year(dicci):

    # Diccionario donde se almacenarán los datos procesados
    dicci2 = {}

    # Listas para guardar los nombres y los años por separado
    peli = []
    ano = []

    # Recorre cada título almacenado en la clave 'Name'
    for i in dicci['Name']:

        # Divide el texto usando " - " como separador
        titulo, year = i.split(" - ")

        # Guarda el nombre de la película
        peli.append(titulo)

        # Guarda el año convertido a entero
        ano.append(int(year))

    # Crea un nuevo diccionario con las columnas separadas
    dicci2 = {
        'Name': peli,
        'Year': ano
    }

    # Convierte el diccionario en un DataFrame
    frame = pd.DataFrame(dicci2)

    # Devuelve el DataFrame resultante
    return frame

In [3]:
# Función que separa el nombre de la película y el año
def extract_year(movies):

    # Listas donde se almacenarán los nombres y años
    nombres = []
    anios = []

    # Recorre cada título de la columna 'Name'
    for titulo in movies['Name']:

        # Divide el texto desde el último " - "
        # El parámetro 1 indica que solo realiza una división
        partes = titulo.rsplit(' - ', 1)

        # Obtiene el nombre de la película
        nombre = partes[0]

        # Obtiene el año de estreno
        anio = partes[1]

        # Guarda los datos en sus respectivas listas
        nombres.append(nombre)
        anios.append(anio)

    # Crea y devuelve un DataFrame con las columnas separadas
    return pd.DataFrame({
        'Name': nombres,
        'Year': anios
    })

In [ ]:
# Función que separa el nombre de la película y el año
def extract_year(movies):

    # Convierte el diccionario de entrada en un DataFrame
    df_movies = pd.DataFrame(movies)

    # Crea la columna "Year" extrayendo el texto después del guion (-)
    # split('-')[1] obtiene la segunda parte y strip() elimina espacios
    df_movies['Year'] = df_movies['Name'].apply(
        lambda x: x.split('-')[1].strip()
    )

    # Reemplaza la columna "Name" dejando únicamente el nombre de la película
    # split('-')[0] obtiene la primera parte antes del guion
    df_movies['Name'] = df_movies['Name'].apply(
        lambda x: x.split('-')[0].strip()
    )

    # Devuelve el DataFrame con las columnas Name y Year separadas
    return df_movies

## 02
- Crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [4]:
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])
expected_output = np.array([False, True, True, False, False, False, False, False, True, False, True, True, False, False])
output = find_duplicates(numbers)   # This calls your function find_duplicates
print(output)
assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10     True
11     True
12    False
13    False
dtype: bool

In [1]:
# Your solution HERE !!!!
# Función que identifica los elementos duplicados de un arreglo
def find_duplicates(numbers):

    # Obtiene los índices de la primera aparición de cada valor único
    _, idx = np.unique(numbers, return_index=True)

    # Crea un arreglo de valores booleanos inicializado en False
    result = np.zeros_like(numbers, dtype=bool)

    # Marca como True las posiciones donde aparece cada valor por primera vez
    result[idx] = True

    # Invierte los valores booleanos:
    # - Las primeras apariciones pasan a False.
    # - Los elementos repetidos pasan a True.
    result = np.invert(result)

    # Devuelve el arreglo indicando qué elementos son duplicados
    return result

In [5]:
# Función que identifica los elementos duplicados de un arreglo
def find_duplicates(numbers):

    # Conjunto para almacenar los valores que ya han aparecido
    visto = set()

    # Lista donde se guardará el resultado
    output = []

    # Recorre cada número del arreglo
    for value in numbers:

        # Si el número ya fue visto, es un duplicado
        if value in visto:
            output.append(True)

        # Si aparece por primera vez, se guarda en el conjunto
        else:
            visto.add(value)
            output.append(False)

    # Convierte la lista de resultados en un arreglo de NumPy
    return np.array(output)

In [4]:
# Función que identifica los elementos duplicados de un arreglo
def find_duplicates(numeros):

    # Diccionario para registrar los valores que ya aparecieron
    dicci = {}

    # Crea un arreglo booleano inicializado en False
    resul = np.full(numeros.shape, False, dtype=bool)

    # Recorre el arreglo obteniendo el índice y el valor
    for idx, valor in enumerate(numeros):

        # Si el valor ya existe en el diccionario, es un duplicado
        if valor in dicci:
            resul[idx] = True

        # Si es la primera vez que aparece, se registra en el diccionario
        else:
            dicci[valor] = True

    # Devuelve un arreglo donde:
    # False = primera aparición
    # True = elemento duplicado
    return resul

In [ ]:
def find_duplicates(numeros):
  dicci={}
  resul=np.full(numeros.shape, False, dtype=bool)
  for idx, valor in enumerate(numeros):
    if valor in dicci:
      resul[idx]=True
    else:
      dicci[valor]=True
  return resul

## 03
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} -9x +  4y = 20 \\ -7y + 16x = 80                         \end{cases}$
    
    - $ B : \begin{cases} x - 2y + 3z = 7 \\ 2x + y + z = 4 \\ -3x + 2y -2z = -10 \end{cases}$
- Verifica por código los resultados

In [ ]:
# Importa la librería para realizar comparaciones de números decimales
import math

# Importa el módulo de álgebra lineal de NumPy
import numpy.linalg as linalg

# ==========================
# Sistema de ecuaciones 2x2
# ==========================

# Matriz de coeficientes
a = np.array([
    [-9, 4],
    [16, -7]
])

# Vector de términos independientes
b = np.array([20, 80])

# Muestra la matriz y el vector
print(a)
print(b)

# Resuelve el sistema de ecuaciones Ax = b
# x contiene las soluciones de las incógnitas
x, y = linalg.solve(a, b)

# Imprime los valores obtenidos
print(f'x={x} y={y}')

# Verifica que las soluciones satisfacen la primera ecuación
print(math.isclose(-9 * x + 4 * y, 20))

# Verifica que las soluciones satisfacen la segunda ecuación
print(math.isclose(16 * x - 7 * y, 80))

# ==========================
# Sistema de ecuaciones 3x3
# ==========================

# Matriz de coeficientes
A2 = np.array([
    [1, -2, 3],
    [2, 1, 1],
    [-3, 2, -2]
])

# Vector de términos independientes
b2 = np.array([7, 4, -10])

# Resuelve el sistema de ecuaciones
x, y, z = np.linalg.solve(A2, b2)

# Imprime los valores obtenidos
print(f'x={x} y={y} z={z}')

# Verifica que la solución cumple la primera ecuación
print(math.isclose(1 * x - 2 * y + 3 * z, 7))

# Verifica que la solución cumple la segunda ecuación
print(math.isclose(2 * x + y + z, 4))

# Verifica que la solución cumple la tercera ecuación
print(math.isclose(-3 * x + 2 * y - 2 * z, -10))

## 04
- Crear un objeto Series con 10 elementos, que contenga más de un tipo básico, con índices de tipo string
- Demuestra que los datos con índices posicionales son los mismos que los obtenidos con índices semánticos, seleccionando a través de slicing, al menos 4 elementos de la serie anterior

In [ ]:
# Your solution HERE !!!!
# Crea una Serie de Pandas con diferentes tipos de datos
# y asigna índices personalizados de la 'a' a la 'j'
serie = pd.Series(
    [1, 2, 3, 4, 5, True, "acelga", 4.5, 9, 10],
    index=list('abcdefghij')
)

# Compara dos formas de acceder a los mismos elementos:
# - loc[:'d'] selecciona por etiquetas (desde 'a' hasta 'd', inclusive).
# - iloc[:4] selecciona por posiciones (de la posición 0 a la 3).
# El resultado será una Serie de valores booleanos indicando si son iguales.
serie.loc[:'d'] == serie.iloc[:4]

In [ ]:
# Crea una Serie con índices personalizados
elementos = pd.Series(
    ['lápiz', '4.13', '33', 'True', 'hola',
     '123', 'arbol', '5.67', 'mesa', '67'],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
)

# Compara dos formas de seleccionar los mismos elementos:
# - [2:6] selecciona por posición (índices 2, 3, 4 y 5).
# - ['c':'f'] selecciona por etiquetas (desde 'c' hasta 'f', inclusive).
# Devuelve una Serie de valores booleanos indicando si ambos resultados son iguales.
print(elementos[2:6] == elementos['c':'f'])

In [ ]:
# Crea una Serie con diferentes tipos de datos
# y etiquetas personalizadas
datos = pd.Series(
    [25, 3.14, "hola", True, 100, "AI", 0.99, False, "Python", 7],
    index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
)

# Compara dos métodos de selección:
# - iloc[2:6] selecciona por posición (2 a 5).
# - loc["c":"f"] selecciona por etiquetas (de "c" hasta "f", inclusive).
# Imprime una Serie de valores booleanos indicando si ambos subconjuntos son iguales.
print(datos.iloc[2:6] == datos.loc["c":"f"])

## 05
- Crear un DataFrame de dimensiones 10x10, con números aleatorios en el rango `[0,20]`
- Reemplazar todos aquellos elementos menores de 5 por NaN
- Averiguar cuantos elementos tienen Nan por fila

In [9]:
# Your solution HERE !!!!
# Crea un DataFrame de 10x10 con números enteros aleatorios entre 0 y 20
df = pd.DataFrame(np.random.randint(21, size=(10, 10)))

# Muestra el DataFrame original
display(df)

# Reemplaza por NaN todos los valores menores que 5
# Los valores mayores o iguales a 5 permanecen sin cambios
df.where(df >= 5, np.nan, inplace=True)

# Muestra el DataFrame después de reemplazar los valores
display(df)

# Cuenta la cantidad de valores NaN en cada fila (axis=1)
print(df.isnull().sum(axis=1))

    0   1   2   3   4   5   6   7   8   9
0   9  14   5  12   6  11  17   0   6   0
1  14  17  13  19   3   1   0   4   9   8
2  19   9  19   3   9  13  18  16  17   6
3  16   6  13  20  20   5  18  19   1  13
4  11  18  15   1   1  15   6  10   9  17
5  20  13   4   7   3  15  19  13   7   9
6   0   9  18   5   9   5   2  11  10   1
7  10   9  11   5  19   3   2   6  20  17
8  14  18  16   8   3   8   4  13   3  13
9   4  15  15  15  13  12   2   8  10   2

      0   1     2     3     4     5     6     7     8     9
0   9.0  14   5.0  12.0   6.0  11.0  17.0   NaN   6.0   NaN
1  14.0  17  13.0  19.0   NaN   NaN   NaN   NaN   9.0   8.0
2  19.0   9  19.0   NaN   9.0  13.0  18.0  16.0  17.0   6.0
3  16.0   6  13.0  20.0  20.0   5.0  18.0  19.0   NaN  13.0
4  11.0  18  15.0   NaN   NaN  15.0   6.0  10.0   9.0  17.0
5  20.0  13   NaN   7.0   NaN  15.0  19.0  13.0   7.0   9.0
6   NaN   9  18.0   5.0   9.0   5.0   NaN  11.0  10.0   NaN
7  10.0   9  11.0   5.0  19.0   NaN   NaN   6.0  20.0  17.0
8  14.0  18  16.0   8.0   NaN   8.0   NaN  13.0   NaN  13.0
9   NaN  15  15.0  15.0  13.0  12.0   NaN   8.0  10.0   NaN

0    2
1    4
2    1
3    1
4    2
5    2
6    3
7    2
8    3
9    3
dtype: int64

In [10]:
# Genera una matriz de 10x10 con números enteros aleatorios entre 0 y 20
matrix = np.random.randint(21, size=(10, 10))

# Convierte la matriz en un DataFrame
frame = pd.DataFrame(matrix)

# Muestra el DataFrame original
display(frame)

# Reemplaza por NaN todos los valores menores que 5
frame[frame < 5] = np.nan

# Cuenta la cantidad de valores NaN en cada fila
nanfila = frame.isna().sum(axis=1)

# Muestra el número de valores faltantes por fila
print(nanfila)

    0   1   2   3   4   5   6   7   8   9
0  17  11  11  12  16  10   5   3  14   8
1   8   9  13  20  10   7  17   4   0  17
2   2  20   4  11  11  18  17   3   0  16
3  17   5  14   4   1  13   5  14   1  17
4  11  17  20   1  11   2   7  13  13  11
5  14   9  17  10   7  19   1   4   1   1
6  14   5   7  15  11  14  18   1  17   5
7   3  16  17   4   2  13   7   8   6   3
8   6   0  19   7   2  10  12  17   2   0
9   6  12  17  15   2  19  18  17  10  19

0    1
1    2
2    4
3    3
4    2
5    4
6    1
7    4
8    4
9    1
dtype: int64

In [11]:
# Crea un DataFrame de 10x10 con números enteros aleatorios entre 0 y 19
df = pd.DataFrame(np.random.randint(0, 20, size=(10, 10)))

# Muestra el DataFrame original
print("DataFrame original:\n", df)

# Reemplaza con NaN todos los valores menores que 5
df[df < 5] = np.nan

# Muestra el DataFrame después del reemplazo
print("\nDataFrame con NaNs:\n", df)

# Cuenta la cantidad de valores NaN en cada fila
nans_por_fila = df.isna().sum(axis=1)

# Muestra el número de valores faltantes por fila
print("\nCantidad de NaNs por fila:\n", nans_por_fila)

DataFrame original:
     0   1   2   3   4   5   6   7   8   9
0  15  12  13  18   2  19  11   0  17   8
1  12   3  13  11   8   6   4  10  19   9
2   3   3  18  19  17   2   8  17  13   5
3   7   8  18  15  19  19   7  11   7   8
4   5   6   2   9   6  12   4  14   1  15
5   1   4  15  18  14   6  10   9  16   0
6   0  15   0   3   8   7  10  17  19  10
7  19   2   8   8   8  11  13   2   6   2
8   4   5  11  14   5  19  16  19   7   1
9  17  10  16  15   9  17  13  11   2   4

DataFrame con NaNs:
       0     1     2     3     4     5     6     7     8     9
0  15.0  12.0  13.0  18.0   NaN  19.0  11.0   NaN  17.0   8.0
1  12.0   NaN  13.0  11.0   8.0   6.0   NaN  10.0  19.0   9.0
2   NaN   NaN  18.0  19.0  17.0   NaN   8.0  17.0  13.0   5.0
3   7.0   8.0  18.0  15.0  19.0  19.0   7.0  11.0   7.0   8.0
4   5.0   6.0   NaN   9.0   6.0  12.0   NaN  14.0   NaN  15.0
5   NaN   NaN  15.0  18.0  14.0   6.0  10.0   9.0  16.0   NaN
6   NaN  15.0   NaN   NaN   8.0   7.0  10.0  17.0  19.0  10.0
7  19.0   NaN   8.0   8.0   8.0  11.0  13.0   NaN   6.0   NaN
8   NaN   5.0  11.0  14.0   5.0  19.0  16.0  19.0   7.0   NaN
9  17.0  10.0  16.0  15.0   9.0  17.0  13.0  11.0   NaN   NaN

Cantidad de NaNs por fila:
 0    2
1    2
2    3
3    0
4    3
5    3
6    3
7    3
8    2
9    2
dtype: int64

## 06
- Dada una lista de elementos, crea una función que devuelva un dataframe sin los elementos duplicados

In [12]:
# Your solution HERE !!!!
# Función que elimina los elementos duplicados de una lista
def remove_duplicates(lista):

    # Convierte la lista en un conjunto (set) para eliminar duplicados
    noduplis = list(set(lista))

    # Convierte la lista de elementos únicos en un DataFrame
    # y asigna el nombre "elementos" a la columna
    df = pd.DataFrame(noduplis, columns=['elementos'])

    # Devuelve el DataFrame resultante
    return df

In [ ]:
# Función que elimina los elementos duplicados de una lista
def remove_duplicates(lista):

    # np.unique() obtiene únicamente los valores únicos de la lista
    # y luego se convierten en un DataFrame
    return pd.DataFrame(np.unique(lista))

In [ ]:
# Función que elimina los elementos duplicados de una lista
def remove_duplicates(lista):

    # dict.fromkeys() elimina los elementos repetidos
    # conservando el orden en el que aparecen en la lista
    unicos = list(dict.fromkeys(lista))

    # Convierte la lista de elementos únicos en un DataFrame
    return pd.DataFrame(unicos)

## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [13]:
l = np.arange(0,5)
print(l)

[0 1 2 3 4]

In [14]:
# Función generadora que produce una secuencia infinita de números
def frange(init, step):

    # Se ejecuta indefinidamente hasta que el usuario detenga el generador
    while True:

        # yield convierte a la función en un generador.
        # Devuelve el valor actual sin finalizar la función,
        # por lo que en la siguiente llamada continuará desde este punto.
        yield init

        # Incrementa el valor según el paso indicado
        init += step

In [20]:
# Importa la librería para comparar números de punto flotante
import math

# Valor inicial de la secuencia
init = 10.6

# Incremento entre cada número generado
step = 0.8

# Crea el generador llamando a la función frange
g = frange(init, step)

# Cantidad de valores que se desean obtener del generador
iters = 10

# Obtiene los primeros 10 valores del generador utilizando next()
numbers = [next(g) for n in range(iters)]

# Recorre los valores generados junto con su índice
for i, n in enumerate(numbers):

    # Comprueba que cada valor sea igual a:
    # valor_inicial + (paso × posición)
    # math.isclose() se utiliza para evitar errores de precisión
    # propios de los números decimales.
    print(f"{i}---{n}"+"\n")
    assert(math.isclose(n, init + (step * i)))

# Muestra la lista de valores generados
print(numbers)

0---10.6

1---11.4

2---12.200000000000001

3---13.000000000000002

4---13.800000000000002

5---14.600000000000003

6---15.400000000000004

7---16.200000000000003

8---17.000000000000004

9---17.800000000000004

[10.6, 11.4, 12.200000000000001, 13.000000000000002, 13.800000000000002, 14.600000000000003, 15.400000000000004, 16.200000000000003, 17.000000000000004, 17.800000000000004]

## 08
- Crear una función que reciba una Serie de Pandas y devuelva esa misma serie, reemplazando los espacios en blanco por el carácter menos frecuente en dicha serie.

In [36]:
serie = pd.Series(list('bba cabc faabba aacbbfe'))
# print(serie)
expected_output = pd.Series(list('bbaecabcefaabbaeaacbbfe'))
output = clean_whitespace_replace(serie)  # This calls your function clean_whitespace_replace
print(output)
assert(expected_output.equals(output))  # This will fail if result is not as expected

Counter({'b': 7, 'a': 7, 'c': 3, 'f': 2, 'e': 1})
0     b
1     b
2     a
3     e
4     c
5     a
6     b
7     c
8     e
9     f
10    a
11    a
12    b
13    b
14    a
15    e
16    a
17    a
18    c
19    b
20    b
21    f
22    e
dtype: str

In [32]:
from collections import Counter

# Función que reemplaza los espacios en blanco por el carácter menos frecuente
def clean_whitespace_replace(seri):

    # dropna():
    # Elimina los valores nulos (NaN) de la Serie para evitar que
    # interfieran en el conteo de caracteres.
    #
    # astype(str):
    # Convierte cada elemento de la Serie al tipo de dato string (cadena),
    # permitiendo aplicar operaciones de texto sobre todos los elementos.
    #
    # ''.join(...):
    # Une todos los elementos de la Serie en una única cadena de texto
    # sin utilizar ningún separador.
    texto = ''.join(seri.dropna().astype(str))

    # Counter():
    # Cuenta cuántas veces aparece cada carácter dentro de la cadena.
    #
    # La comprensión:
    # (i for i in texto if i != '')
    # recorre cada carácter de la cadena y lo envía al contador.
    frecu = Counter(i for i in texto if i != ' ')
    print(frecu)

    # min():
    # Obtiene el carácter cuya frecuencia es la menor.
    #
    # key=frecu.get indica que la comparación se realiza utilizando
    # la cantidad de apariciones de cada carácter almacenada en Counter.
    mefrecu = min(frecu, key=frecu.get)

    # astype(str):
    # Convierte nuevamente todos los elementos de la Serie a cadenas.
    #
    # apply():
    # Recorre cada elemento de la Serie y aplica la función indicada.
    #
    # lambda s:
    # Función anónima que recibe cada elemento de la Serie.
    #
    # replace(' ', mefrecu):
    # Sustituye cada espacio en blanco (' ') por el carácter
    # menos frecuente encontrado anteriormente.
    seridif = seri.astype(str).apply(
        lambda s: s.replace(' ', mefrecu)
    )

    # Devuelve la Serie con los espacios reemplazados
    return seridif